MvcApp/ViewModels/User/UserChatMessageViewModel.cs
namespace MvcApp.ViewModels.User
{
    public class UserChatMessageViewModel
    {
        public string Text { get; set; }

        public string AuthorId { get; set; }

        public string AuthorName { get; set; }
    }
}

MvcApp/ViewModels/User/UserDataPairViewModel.cs
namespace MvcApp.ViewModels.User
{
    public class UserDataPairViewModel
    {
        public string Title { get; set; }

        public string Value { get; set; }
    }
}

MvcApp/ViewModels/User/UserEditPhotoInfo.cs
using System.ComponentModel.DataAnnotations;

using MvcApp.Properties;

namespace MvcApp.ViewModels.User
{
    public class UserEditPhotoInfo
    {
        [Url]
        [Display(ResourceType = typeof (Resources), Name = "image_url")]
        public string ImageUrl { get; set; }

        public string Image { get; set; }

        public bool IsBase64 { get; set; }

        public int HasChanged { get; set; }
    }
}

MvcApp/ViewModels/User/UserEditViewModel.cs
using System.ComponentModel.DataAnnotations;

using MvcApp.Data.Models;
using MvcApp.Properties;

namespace MvcApp.ViewModels.User
{
    public class UserEditViewModel
    {
        [RegularExpression("([a-zA-Zа-яА-Я0-9 ]+)", ErrorMessageResourceType = typeof (Resources), ErrorMessageResourceName = "field_contains_invalid_characters")]
        [Display(ResourceType = typeof (Resources), Name = "first_name")]
        public string FirstName { get; set; }

        [RegularExpression("([a-zA-Zа-яА-Я0-9 ]+)", ErrorMessageResourceType = typeof (Resources), ErrorMessageResourceName = "field_contains_invalid_characters")]
        [Display(ResourceType = typeof (Resources), Name = "last_name")]
        public string LastName { get; set; }

        [DataType(DataType.Date)]
        [Display(ResourceType = typeof (Resources), Name = "birth_date")]
        public string BirthDate { get; set; }

        [Display(ResourceType = typeof (Resources), Name = "user_sex")]
        public UserSex Sex { get; set; }

        [Display(ResourceType = typeof (Resources), Name = "user_info")]
        public string Info { get; set; }
    }
}

MvcApp/ViewModels/User/UserFriendListViewModel.cs
using System.Collections.Generic;

namespace MvcApp.ViewModels.User
{
    public class UserFriendListViewModel
    {
        public IEnumerable<UserListEntryViewModel> Friends { get; set; }

        public IEnumerable<UserListEntryViewModel> Subscribers { get; set; }
    }
}

MvcApp/ViewModels/User/UserListEntryViewModel.cs
namespace MvcApp.ViewModels.User
{
    public class UserListEntryViewModel
    {
        public string UserId { get; set; }

        public string UserName { get; set; }
    }
}

MvcApp/ViewModels/User/UserProfileViewModel.cs
using System.Collections.Generic;

namespace MvcApp.ViewModels.User
{
    public class UserProfileViewModel
    {
        public IEnumerable<UserDataPairViewModel> DataPairs;

        public string Id { get; set; }

        public bool IsOwner { get; set; }

        public bool IsFriend { get; set; }

        public string Email { get; set; }

        public string Photo { get; set; }

        public int Rating { get; set; }

        public int PublicationsCount { get; set; }

        public int FavoritesCount { get; set; }
    }
}

MvcApp/Controllers/FriendController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;

using MvcApp.Extensions;

namespace MvcApp.Controllers
{
    [Authorize]
    public class FriendController : BaseController
    {
        [HttpGet]
        public async Task<ActionResult> List()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            return View(user.GetFriendList());
        }

        [HttpPost]
        public async Task<ActionResult> ToggleState(string id)
        {
            if (!Request.IsAjaxRequest())
            {
                return new HttpNotFoundResult();
            }

            var userId = id ?? String.Empty;

            var seekingUser = DbContext.Users.FirstOrDefault(v => v.Id == userId);

            if (!seekingUser.Exists())
            {
                return new HttpNotFoundResult();
            }

            var currentUser = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            if (currentUser.Id == userId) // нельзя добавлять себя в друзья или удалить себя из друзей
            {
                return new HttpStatusCodeResult(HttpStatusCode.MethodNotAllowed);
            }

            var friend = currentUser.Friends.FirstOrDefault(v => v.Id == userId);

            if (friend != null)
            {
                currentUser.Friends.Remove(friend);
            }
            else
            {
                currentUser.Friends.Add(seekingUser);
            }

            await DbContext.SaveChangesAsync();

            return Json(friend == null);
        }
    }
}

MvcApp/Controllers/PublicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;

using MvcApp.Data.Models;
using MvcApp.Extensions;
using MvcApp.Properties;
using MvcApp.Utils;
using MvcApp.ViewModels;
using MvcApp.ViewModels.Publication;

namespace MvcApp.Controllers
{
    public class PublicationController : BaseController
    {
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Search(PublicationSearchViewModel searchParams)
        {
            ViewBag.Publications = DbContext.FindPublicationsByParams(searchParams);

            return View(searchParams);
        }

        private async Task<ActionResult> UserPublicationList(string id,
            Func<UserInfo, IEnumerable<PublicationListEntryViewModel>> func)
        {
            var user = await UserManager.FindByIdAsync(id ?? String.Empty);

            if (!user.Exists())
            {
                return Message(MessageStatus.Danger, Resources.user_not_found);
            }

            UserInfo currentUser = null;

            if (Request.IsAuthenticated)
            {
                currentUser = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            }

            return
                View(new PublicationUserListViewModel
                {
                    UserId = user.Id,
                    UserName = user.GetUserName(),
                    IsOwner = currentUser != null && currentUser.Id == user.Id,
                    Publications = func(user)
                });
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> UserList(string id)
        {
            return await UserPublicationList(id, user => user.Publications.ToList().Select(v => v.ToListEntry()));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> UserFavList(string id)
        {
            return await UserPublicationList(id, user => user.Favorites.ToList().Select(v => v.ToListEntry()));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> Show(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Search");
            }

            var publication = DbContext.Publications.FirstOrDefault(v => v.Id == id);

            if (publication == null)
            {
                return Message(MessageStatus.Danger, Resources.publication_not_found);
            }

            publication.Views++;

            await DbContext.SaveChangesAsync();

            UserInfo currentUser = null;

            if (Request.IsAuthenticated)
            {
                currentUser = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            }

            return View(publication.Render(currentUser));
        }

        [HttpGet]
        [Authorize]
        public ActionResult New()
        {
            return View("PublicationEditor", new PublicationEditViewModel {Id = -1});
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            var publication = DbContext.Publications.FirstOrDefault(v => v.Id == id);

            if (publication == null)
            {
                return Message(MessageStatus.Danger, Resources.publication_not_found);
            }

            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            if (user.Id != publication.Author.Id) // только автор может редактировать публикацию
            {
                return Message(MessageStatus.Danger, Resources.no_publication_editing_permission);
            }

            return View("PublicationEditor", publication.GetEditableData());
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(PublicationEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("PublicationEditor", viewModel);
            }

            // проверка на корректность разметки и отсутствие скриптов

            var verificationResult = PublicationHelper.VerifyContent(viewModel.Content);

            if (verificationResult != PublicationVerificationResult.Success)
            {
                ModelState.AddModelError(String.Empty,
                    verificationResult == PublicationVerificationResult.InvalidMarkup
                        ? Resources.invalid_markup
                        : Resources.js_unallowed);

                return View("PublicationEditor", viewModel);
            }

            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            if (viewModel.Id > 0) // обновление
            {
                var publication = DbContext.Publications.FirstOrDefault(v => v.Id == viewModel.Id);

                if (publication == null)
                {
                    return Message(MessageStatus.Danger, Resources.publication_not_found);
                }

                publication.SaveEditedData(viewModel);

                await DbContext.SaveChangesAsync();

                return RedirectToAction("Show", new {id = publication.Id});
            }
            else // создание
            {
                var publication = new PublicationInfo {Author = user, CreationDate = DateTime.Now};

                publication.SaveEditedData(viewModel);

                DbContext.Publications.Add(publication);

                await DbContext.SaveChangesAsync();

                return RedirectToAction("Show", new {id = publication.Id});
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            if (!Request.IsAjaxRequest())
            {
                return new HttpNotFoundResult();
            }

            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            var publication = DbContext.Publications.FirstOrDefault(v => v.Id == id);

            if (publication == null)
            {
                return new HttpNotFoundResult();
            }

            if (publication.Author.Id != user.Id) // только автор может удалять свои публикации
            {
                return new HttpStatusCodeResult(HttpStatusCode.MethodNotAllowed);
            }

            DbContext.Publications.Remove(publication);

            await DbContext.SaveChangesAsync();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> ToggleRating(int id)
        {
            if (!Request.IsAjaxRequest())
            {
                return new HttpNotFoundResult();
            }

            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            var publication = DbContext.Publications.FirstOrDefault(v => v.Id == id);

            if (publication == null)
            {
                return new HttpNotFoundResult();
            }

            if (publication.Author.Id == user.Id) // автор не может лайкать свои публикации
            {
                return new HttpStatusCodeResult(HttpStatusCode.MethodNotAllowed);
            }

            var rated = user.Rated.FirstOrDefault(v => v.Id == publication.Id);

            if (rated != null)
            {
                user.Rated.Remove(rated);
            }
            else
            {
                user.Rated.Add(publication);
            }

            await DbContext.SaveChangesAsync();

            return Json(new PublicationRatingViewModel {Rated = rated == null, Count = publication.WhoRated.Count()});
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> ToggleFavouriteState(int id)
        {
            if (!Request.IsAjaxRequest())
            {
                return new HttpNotFoundResult();
            }

            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            var publication = DbContext.Publications.FirstOrDefault(v => v.Id == id);

            if (publication == null)
            {
                return new HttpNotFoundResult();
            }

            if (publication.Author.Id == user.Id) // автор не может добавлять в избранное свои публикации
            {
                return new HttpStatusCodeResult(HttpStatusCode.MethodNotAllowed);
            }

            var isFavourite = user.Favorites.FirstOrDefault(v => v.Id == publication.Id);

            if (isFavourite != null)
            {
                user.Favorites.Remove(publication);
            }
            else
            {
                user.Favorites.Add(publication);
            }

            await DbContext.SaveChangesAsync();

            return Json(isFavourite == null);
        }
    }
}

MvcApp/Controllers/UserController.cs
using System;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;

using MvcApp.Data.Models;
using MvcApp.Extensions;
using MvcApp.Properties;
using MvcApp.ViewModels;
using MvcApp.ViewModels.User;

namespace MvcApp.Controllers
{
    public class UserController : BaseController
    {
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Search(string query)
        {
            var users = DbContext.FindUsersByTextQuery(query);

            return Json(users);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> Info(string id)
        {
            var user = await UserManager.FindByIdAsync(id ?? String.Empty);

            if (!user.Exists())
            {
                return Message(MessageStatus.Danger, Resources.user_not_found);
            }

            UserInfo currentUser = null;

            if (Request.IsAuthenticated)
            {
                currentUser = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            }

            return View(user.GetProfileData(currentUser));
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Edit()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            return View(user.GetEditableData());
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UserEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            user.SaveEditedData(viewModel);

            await DbContext.SaveChangesAsync();

            return RedirectToAction("Info", new {id = user.Id});
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> EditPhoto()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            return View(user.GetEditablePhotoData());
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditPhoto(UserEditPhotoInfo viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            await user.SaveEditedPhoto(viewModel, Request.PhysicalApplicationPath);

            await DbContext.SaveChangesAsync();

            return RedirectToAction("Info", new {id = user.Id});
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Chat(string id)
        {
            var user = await UserManager.FindByIdAsync(id ?? String.Empty);

            if (!user.Exists())
            {
                return Message(MessageStatus.Danger, Resources.user_not_found);
            }

            if (user.Id == User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(HttpStatusCode.MethodNotAllowed);
            }

            ViewBag.UserName = user.Email;

            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> ChatHistory(string id)
        {
            var user = await UserManager.FindByEmailAsync(id ?? String.Empty);

            if (!user.Exists())
            {
                return new HttpNotFoundResult();
            }

            var currentUser = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            return Json(DbContext.GetChatHistory(currentUser.Id, user.Id));
        }
    }
}

MvcApp/Views/User/Chat.cshtml
@using System.Web.Optimization
@using MvcApp.Properties
@{
    ViewBag.Title = Resources.chat;
}
@section Styles {
    <style type="text/css">
        
    </style>
}
<div class="row">
    <div class="col-md-offset-1 col-md-10">
        <div class="input-group">
            <input id="message_text" type="text" class="form-control" placeholder="@(Resources.message + " - " + ViewBag.UserName)">
            <span class="input-group-btn">
                <button id="send_message_btn" class="btn btn-success" type="button" data-loading-text="@Resources.loading">@Resources.send</button>
            </span>
        </div>
    </div>

</div>
<div class="row">
    <div class="col-md-offset-1 col-md-10">
        <div id="messages"></div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/chatjs")
    <script>
        $(document).ready(function() {
            new ChatController("@ViewBag.UserName");
        });
    </script>
}
@section Template {
    <script id="message_template" type="text/template">
        <div>
            <hr />
            <div>
                <div>
                    <b>
                        <small>
                            <a href="@Url.Action("Info", "User")/{{AuthorId}}" target="_blank">{{AuthorName}}</a>
                        </small>
                    </b>
                    &nbsp;
                </div>
                <div>
                    <blockquote>
                        <small class="comment">{{Text}}
                        </small>
                    </blockquote>
                </div>
            </div>
        </div>
    </script>
}

MvcApp/Views/User/Edit.cshtml
@using MvcApp.Data.Models
@using MvcApp.Properties
@model MvcApp.ViewModels.User.UserEditViewModel
@{
    ViewBag.Title = Resources.edit_profile;
}
@section Styles {
    <style type="text/css">
        #@(Html.IdFor(m => m.Info)) {
            height: 150px;
            resize: none;
        }

        .datepicker { margin: 0 auto; }
    </style>
}
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="text-center">
                    <h3>@Resources.edit_profile</h3>
                </div>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("Edit", "User", FormMethod.Post, new
                {
                    @class = "form-horizontal"
                }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group space-from-above">
                        @Html.ValidationSummary(true, String.Empty, new
                        {
                            @class = "text-danger"
                        })
                    </div>
                    <div class="form-group space-from-above">
                        @Html.LabelFor(m => m.FirstName, new
                        {
                            @class = "col-md-4 control-label"
                        })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.FirstName, new
                            {
                                @class = "form-control"
                            })
                            @Html.ValidationMessageFor(m => m.FirstName, String.Empty, new
                            {
                                @class = "text-danger"
                            })
                        </div>
                    </div>
                    <div class="form-group space-from-above">
                        @Html.LabelFor(m => m.LastName, new
                        {
                            @class = "col-md-4 control-label"
                        })
                        <div class="col-md-6">
                            @Html.TextBoxFor(m => m.LastName, new
                            {
                                @class = "form-control"
                            })
                            @Html.ValidationMessageFor(m => m.LastName, String.Empty, new
                            {
                                @class = "text-danger"
                            })
                        </div>
                    </div>
                    <div class="form-group space-from-above">
                        @Html.LabelFor(m => m.Sex, new
                        {
                            @class = "col-md-4 control-label"
                        })
                        <div class="col-md-6">
                            <div class="text-center">
                                <div class="radio-inline">
                                    @Html.RadioButtonFor(m => m.Sex, UserSex.Male)
                                    @Html.Label("М")
                                </div>
                                <div class="radio-inline">
                                    @Html.RadioButtonFor(m => m.Sex, UserSex.Female)
                                    @Html.Label("Ж")
                                </div>
                                <div class="radio-inline">
                                    @Html.RadioButtonFor(m => m.Sex, UserSex.NotSpecified)
                                    @Html.Label("Не указан")
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group space-from-above">
                        @Html.LabelFor(m => m.BirthDate, new
                        {
                            @class = "col-md-4 control-label"
                        })

                        <div class="col-md-6">
                            @Html.HiddenFor(m => m.BirthDate)
                            <div id="datepicker" class="text-center" data-date="@Html.ValueFor(m => m.BirthDate)"></div>
                        </div>
                    </div>
                    <div class="form-group space-from-above">
                        @Html.LabelFor(m => m.Info, new
                        {
                            @class = "col-md-4 control-label"
                        })
                        <div class="col-md-6">
                            @Html.TextAreaFor(m => m.Info, new
                            {
                                @class = "form-control"
                            })
                        </div>
                    </div>
                    <div class="form-group space-from-above">
                        <div class="col-md-offset-4 col-md-6">
                            <button type="submit" class="btn btn-primary">@Resources.save</button>
                            &nbsp;
                            <button id="clear_date_btn" type="button" class="btn btn-link">@Resources.clear_date</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function() {
            $("#datepicker").datepicker({
                language: "ru",
                todayHighlight: true,
                endDate: new Date()
            }).on("changeDate", function(e) {
                $("#@(Html.IdFor(m => m.BirthDate))").val(e.format());
            });
            $("#clear_date_btn").click(function() {
                $("#@(Html.IdFor(m => m.BirthDate))").val("");
                $("#datepicker").datepicker("update", new Date());
            });
        });
    </script>
}

MvcApp/Views/User/Info.cshtml
@using MvcApp.Properties
@model MvcApp.ViewModels.User.UserProfileViewModel
@{
    ViewBag.Title = Resources.profile;
}
@section Styles {
    <style type="text/css">
        #avatar {
            height: 200px;
            width: 200px;
        }
    </style>
}
<div class="row">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-3">
                    <img id="avatar" class="img-thumbnail" alt="" src="@Html.ValueFor(m => m.Photo)"/>
                </div>
                <div class="col-md-9">
                    <h2 class="page-header">@Model.Email</h2>
                    <h3>
                        @Resources.rating - @Model.Rating
                    </h3>
                    @if (Request.IsAuthenticated && !Model.IsOwner)
                    {
                        <div class="text-right">
                            <a href="@Url.Action("Chat", new{id = Model.Id})" class="btn btn-default">@Resources.chat</a>
                            <button id="toggle_friend_state_btn" class="btn" data-user-id="@Model.Id"></button>
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="panel-body">
            <ul class="nav nav-pills nav-justified">
                <li role="presentation">
                        <a href="@Url.Action("UserList", "Publication", new {id = Model.Id})">
                            <b>
                                @Resources.publications <span class="label label-success">@Model.PublicationsCount</span>
                            </b>
                            
                        </a>
                </li>
                <li role="presentation">
                    <a href="@Url.Action("UserFavList", "Publication", new {id = Model.Id})">
                        <b>
                            @Resources.favorites <span class="label label-success">@Model.FavoritesCount</span>
                        </b>
                    </a>
                </li>
            </ul>
            <div>
                @foreach (var dataPair in Model.DataPairs)
                {
                    <hr />
                    <div class="row">
                        <div class="col-md-3">
                            <strong>@dataPair.Title</strong>
                        </div>
                        <div class="col-md-9">
                            @dataPair.Value
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@if (Request.IsAuthenticated && !Model.IsOwner)
{
    @section Scripts {
        <script type="text/javascript">
            $(document).ready(function() {
                var updateFriendState = function(isFriend) {
                    var toggleBtn = $("#toggle_friend_state_btn");
                    toggleBtn.removeClass("btn-danger").removeClass("btn-success").
                        addClass(isFriend ? "btn-danger" : "btn-success").
                        text(isFriend ? "@Resources.remove_from_friends" : "@Resources.add_to_friends");
                };
                $("#toggle_friend_state_btn").click(function() {
                    var userId = $(this).data("user-id");
                    $.post("@Url.Action("ToggleState", "Friend")", {
                        id: userId
                    }, function(response) {
                        updateFriendState(response);
                    });
                });
                updateFriendState(@(Model.IsFriend ? 1 : 0));
            });
        </script>
    }
}